sudo: required

services:
  - docker

script:
  - docker build -name zitsen/docker-opensnp-datadump
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push zitsen/docker-opensnp-datadump;
    fi

